# config/services.yaml

parameters:
    avatars_directory: '%kernel.project_dir%/public/uploads/avatars'
    photos_directory: '%kernel.project_dir%/public/uploads/photos'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'

services:
    _defaults:
        autowire: true       # Injection automatique des dépendances
        autoconfigure: true  # Enregistre automatiquement les services (ex: commandes, événements, etc.)

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Déclaration explicite si tu utilises ce service personnalisé
    
    App\Service\UserProfileService: ~
    App\Service\NavbarNotificationService: ~
    

    # Enregistrement d'une extension Twig personnalisée
    App\Twig\AppExtension:
        tags: [ 'twig.extension' ]
